# Generated by Django 4.0.1 on 2022-06-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Descripción'),
        ),
    ]
