# Generated by Django 4.0.1 on 2022-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_direccion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50, verbose_name='Estado del envio')),
            ],
        ),
    ]
