# Generated by Django 4.0.1 on 2022-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0009_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='donado',
        ),
        migrations.AddField(
            model_name='donacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
